# Imports

In [6]:
import pandas as pd
import numpy as np

from pandas.plotting import scatter_matrix

import matplotlib.pyplot as plt
from pylab import rcParams

In [7]:
import sklearn
from sklearn import preprocessing

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict

from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score

# Getting Dataframe from Data

In [8]:
path = r'C:\Users\Mohit\Desktop\ML-Cricket-Integration-Project\Data\Prepared_for_ML_Data.csv'
player_balls = pd.read_csv(path)

In [9]:
player_balls.head()

Unnamed: 0  ODI  T20  Test  Australia  England  India  New Zealand  \
0           0  0.0  0.0   1.0        0.0      0.0    1.0          0.0   
1           1  0.0  0.0   1.0        0.0      0.0    1.0          0.0   
2           2  0.0  0.0   1.0        0.0      0.0    1.0          0.0   
3           3  0.0  0.0   1.0        0.0      0.0    1.0          0.0   
4           4  0.0  0.0   1.0        0.0      0.0    1.0          0.0   

   South Africa  Sri Lanka  ...  Length: Full  Length: Good  Length: Short  \
0           0.0        0.0  ...           0.0           0.0            1.0   
1           0.0        0.0  ...           1.0           0.0            0.0   
2           0.0        0.0  ...           1.0           0.0            0.0   
3           0.0        0.0  ...           0.0           1.0            0.0   
4           0.0        0.0  ...           0.0           0.0            0.0   

   Line: Leg Stump  Line: Legside  Line: Middle Stump  Line: Off Stump  \
0              0.0            0.0                 0.0              0.0   
1              0.0            0.0                 1.0              0.0   
2              0.0            0.0                 1.0              0.0   
3              0.0            0.0                 0.0              0.0   
4              0.0            0.0                 0.0              1.0   

   Line: Offside  Line: Wide Outside Off  Out  
0            0.0                     1.0    0  
1            0.0                     0.0    0  
2            0.0                     0.0    0  
3            1.0                     0.0    0  
4            0.0                     0.0    0  

[5 rows x 30 columns]

In [10]:
# Removing the Unnamed: 0 column
player_balls.drop(['Unnamed: 0'], axis = 1, inplace = True)
player_balls.head()

ODI  T20  Test  Australia  England  India  New Zealand  South Africa  \
0  0.0  0.0   1.0        0.0      0.0    1.0          0.0           0.0   
1  0.0  0.0   1.0        0.0      0.0    1.0          0.0           0.0   
2  0.0  0.0   1.0        0.0      0.0    1.0          0.0           0.0   
3  0.0  0.0   1.0        0.0      0.0    1.0          0.0           0.0   
4  0.0  0.0   1.0        0.0      0.0    1.0          0.0           0.0   

   Sri Lanka  USA  ...  Length: Full  Length: Good  Length: Short  \
0        0.0  0.0  ...           0.0           0.0            1.0   
1        0.0  0.0  ...           1.0           0.0            0.0   
2        0.0  0.0  ...           1.0           0.0            0.0   
3        0.0  0.0  ...           0.0           1.0            0.0   
4        0.0  0.0  ...           0.0           0.0            0.0   

   Line: Leg Stump  Line: Legside  Line: Middle Stump  Line: Off Stump  \
0              0.0            0.0                 0.0              0.0   
1              0.0            0.0                 1.0              0.0   
2              0.0            0.0                 1.0              0.0   
3              0.0            0.0                 0.0              0.0   
4              0.0            0.0                 0.0              1.0   

   Line: Offside  Line: Wide Outside Off  Out  
0            0.0                     1.0    0  
1            0.0                     0.0    0  
2            0.0                     0.0    0  
3            1.0                     0.0    0  
4            0.0                     0.0    0  

[5 rows x 29 columns]

# Logistic Regression

### Breaking Data into Training and Testing

In [24]:
# Splitting the data randomly between the 4 variables
# Need to drop Out column from X_train and X_test since that's what we are going to predict
# Test size is 0.2 because we want the testing data to be 20% of the original data
train_features, test_features, train_result, test_result = train_test_split(player_balls.drop(['Out'], axis = 1), player_balls['Out'], test_size = 0.20)

In [25]:
train_features.head()

ODI  T20  Test  Australia  England  India  New Zealand  South Africa  \
4302  1.0  0.0   0.0        0.0      0.0    1.0          0.0           0.0   
9657  1.0  0.0   0.0        0.0      1.0    0.0          0.0           0.0   
1311  0.0  0.0   1.0        0.0      0.0    1.0          0.0           0.0   
8884  1.0  0.0   0.0        0.0      0.0    0.0          0.0           1.0   
5224  0.0  0.0   1.0        0.0      0.0    0.0          0.0           1.0   

      Sri Lanka  USA  ...  Length: Back of a Length  Length: Full  \
4302        0.0  0.0  ...                       0.0           0.0   
9657        0.0  0.0  ...                       0.0           1.0   
1311        0.0  0.0  ...                       0.0           1.0   
8884        0.0  0.0  ...                       0.0           0.0   
5224        0.0  0.0  ...                       0.0           0.0   

      Length: Good  Length: Short  Line: Leg Stump  Line: Legside  \
4302           1.0            0.0              0.0            0.0   
9657           0.0            0.0              0.0            0.0   
1311           0.0            0.0              0.0            0.0   
8884           0.0            1.0              0.0            0.0   
5224           1.0            0.0              0.0            0.0   

      Line: Middle Stump  Line: Off Stump  Line: Offside  \
4302                 1.0              0.0            0.0   
9657                 1.0              0.0            0.0   
1311                 0.0              1.0            0.0   
8884                 0.0              1.0            0.0   
5224                 0.0              0.0            1.0   

      Line: Wide Outside Off  
4302                     0.0  
9657                     0.0  
1311                     0.0  
8884                     0.0  
5224                     0.0  

[5 rows x 28 columns]

In [26]:
train_result.head()

4302    0
9657    0
1311    0
8884    0
5224    0
Name: Out, dtype: int64

In [28]:
print(len(train_features))
print(len(test_features))

8693
2174


### Deploying the Model

In [29]:
# Training the Model
Log_Reg = LogisticRegression(solver = 'liblinear')
Log_Reg.fit(train_features, train_result)

LogisticRegression(solver='liblinear')

In [31]:
# Feeding new data to our trained model
test_prediction = Log_Reg.predict(test_features)

# Model Evaluation

### Classification Report without Cross-Validation

In [32]:
print(classification_report(test_result, test_prediction))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2138
           1       0.00      0.00      0.00        36

    accuracy                           0.98      2174
   macro avg       0.49      0.50      0.50      2174
weighted avg       0.97      0.98      0.98      2174



c:\Users\Mohit\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Mohit\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Mohit\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### K-Fold Cross-Validation & Confusion Matrices

In [47]:
# The matrix tells us that 73 are the correct number of predictions for 0 and 45 are the incorrect predictions
# We made 57 correct predictions for 1 and 58 incorrect predictions for 1
Y_train_pred = cross_val_predict(Log_Reg, train_features, train_result, cv = 5)
train_accuracy = metrics.accuracy_score(train_result, Log_Reg.predict(train_features))
test_accuracy = metrics.accuracy_score(test_result, test_prediction)

print('Train Accuracy: ', train_accuracy)
print('Test Accuracy: ', test_accuracy)
confusion_matrix(train_result, Y_train_pred)

Train Accuracy:  0.9873461405728747
Test Accuracy:  0.983440662373505


array([[8583,    0],
       [ 110,    0]], dtype=int64)

In [48]:
# Precision of the model
precision_score(train_result, Y_train_pred)

c:\Users\Mohit\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.0

# Making a Test Prediction

In [91]:
getting_ball = pd.Series.to_numpy(player_balls.iloc[5000]).reshape(1, -1)
sample_ball = getting_ball[0][0:28].reshape(1, -1)
sample_ball

array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1., 77.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
         0.,  0.]])

In [92]:
print(Log_Reg.predict(sample_ball)) # the prediction
print(Log_Reg.predict_proba(sample_ball)) # probability of the prediction being correct (77.8%)

[0]
[[0.99036169 0.00963831]]
